tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "coreutils"
brew "openssl@1.1"
brew "readline"
brew "asdf"
brew "curl"
brew "git"
brew "gnupg"
brew "m-cli"
brew "mas"
brew "node"
brew "sqlite"
brew "xz"
brew "zlib"
cask "1password"
cask "android-file-transfer"
cask "blue-sherpa"
cask "brave-browser"
cask "docker"
cask "firefox-developer-edition"
cask "font-hack-nerd-font"
cask "font-inconsolata-dz-for-powerline"
cask "franz"
cask "google-chrome"
cask "iterm2"
cask "kap"
cask "logitech-g-hub"
cask "mysqlworkbench"
cask "ngrok"
cask "omnidisksweeper"
cask "postico"
cask "postman"
cask "safari-technology-preview"
cask "spotify"
cask "steam"
cask "sublime-text"
cask "visual-studio-code"
cask "vlc"
cask "zoom"
mas "Apple Configurator 2", id: 1037126344
mas "Magnet", id: 441258766
mas "Skitch", id: 425955336
mas "Slack", id: 803453959
mas "Xcode", id: 497799835
